/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StarterGuideRouteImport } from './routes/starter-guide'
import { Route as ReviewMethodologyRouteImport } from './routes/review-methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MedicalReviewPolicyRouteImport } from './routes/medical-review-policy'
import { Route as HowWeResearchRouteImport } from './routes/how-we-research'
import { Route as GearRouteImport } from './routes/gear'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as CorrectionsPolicyRouteImport } from './routes/corrections-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as ComparisonsRouteImport } from './routes/comparisons'
import { Route as BestRouteImport } from './routes/best'
import { Route as AiImageryPolicyRouteImport } from './routes/ai-imagery-policy'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as PosesIndexRouteImport } from './routes/poses/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GoIndexRouteImport } from './routes/go/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ReviewsRetrospecRouteImport } from './routes/reviews/retrospec'
import { Route as ReviewsMandukaProRouteImport } from './routes/reviews/manduka-pro'
import { Route as ReviewsMandukaGrpAdaptRouteImport } from './routes/reviews/manduka-grp-adapt'
import { Route as ReviewsLululemonRouteImport } from './routes/reviews/lululemon'
import { Route as ReviewsLiformeRouteImport } from './routes/reviews/liforme'
import { Route as ReviewsJadeRouteImport } from './routes/reviews/jade'
import { Route as ReviewsGaiamRouteImport } from './routes/reviews/gaiam'
import { Route as ReviewsBestYogaMatsRouteImport } from './routes/reviews/best-yoga-mats'
import { Route as ReviewsAloRouteImport } from './routes/reviews/alo'
import { Route as PosesSlugRouteImport } from './routes/poses/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors/$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterGuideRoute = StarterGuideRouteImport.update({
  id: '/starter-guide',
  path: '/starter-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewMethodologyRoute = ReviewMethodologyRouteImport.update({
  id: '/review-methodology',
  path: '/review-methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalReviewPolicyRoute = MedicalReviewPolicyRouteImport.update({
  id: '/medical-review-policy',
  path: '/medical-review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeResearchRoute = HowWeResearchRouteImport.update({
  id: '/how-we-research',
  path: '/how-we-research',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsPolicyRoute = CorrectionsPolicyRouteImport.update({
  id: '/corrections-policy',
  path: '/corrections-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonsRoute = ComparisonsRouteImport.update({
  id: '/comparisons',
  path: '/comparisons',
  getParentRoute: () => rootRouteImport,
} as any)
const BestRoute = BestRouteImport.update({
  id: '/best',
  path: '/best',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageryPolicyRoute = AiImageryPolicyRouteImport.update({
  id: '/ai-imagery-policy',
  path: '/ai-imagery-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosesIndexRoute = PosesIndexRouteImport.update({
  id: '/poses/',
  path: '/poses/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoIndexRoute = GoIndexRouteImport.update({
  id: '/go/',
  path: '/go/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRetrospecRoute = ReviewsRetrospecRouteImport.update({
  id: '/reviews/retrospec',
  path: '/reviews/retrospec',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsMandukaProRoute = ReviewsMandukaProRouteImport.update({
  id: '/reviews/manduka-pro',
  path: '/reviews/manduka-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsMandukaGrpAdaptRoute = ReviewsMandukaGrpAdaptRouteImport.update({
  id: '/reviews/manduka-grp-adapt',
  path: '/reviews/manduka-grp-adapt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsLululemonRoute = ReviewsLululemonRouteImport.update({
  id: '/reviews/lululemon',
  path: '/reviews/lululemon',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsLiformeRoute = ReviewsLiformeRouteImport.update({
  id: '/reviews/liforme',
  path: '/reviews/liforme',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsJadeRoute = ReviewsJadeRouteImport.update({
  id: '/reviews/jade',
  path: '/reviews/jade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsGaiamRoute = ReviewsGaiamRouteImport.update({
  id: '/reviews/gaiam',
  path: '/reviews/gaiam',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsBestYogaMatsRoute = ReviewsBestYogaMatsRouteImport.update({
  id: '/reviews/best-yoga-mats',
  path: '/reviews/best-yoga-mats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsAloRoute = ReviewsAloRouteImport.update({
  id: '/reviews/alo',
  path: '/reviews/alo',
  getParentRoute: () => rootRouteImport,
} as any)
const PosesSlugRoute = PosesSlugRouteImport.update({
  id: '/poses/$slug',
  path: '/poses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/ai-imagery-policy': typeof AiImageryPolicyRoute
  '/best': typeof BestRoute
  '/comparisons': typeof ComparisonsRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/gear': typeof GearRoute
  '/how-we-research': typeof HowWeResearchRoute
  '/medical-review-policy': typeof MedicalReviewPolicyRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/review-methodology': typeof ReviewMethodologyRoute
  '/starter-guide': typeof StarterGuideRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/reviews/alo': typeof ReviewsAloRoute
  '/reviews/best-yoga-mats': typeof ReviewsBestYogaMatsRoute
  '/reviews/gaiam': typeof ReviewsGaiamRoute
  '/reviews/jade': typeof ReviewsJadeRoute
  '/reviews/liforme': typeof ReviewsLiformeRoute
  '/reviews/lululemon': typeof ReviewsLululemonRoute
  '/reviews/manduka-grp-adapt': typeof ReviewsMandukaGrpAdaptRoute
  '/reviews/manduka-pro': typeof ReviewsMandukaProRoute
  '/reviews/retrospec': typeof ReviewsRetrospecRoute
  '/blog/': typeof BlogIndexRoute
  '/go/': typeof GoIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/poses/': typeof PosesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/ai-imagery-policy': typeof AiImageryPolicyRoute
  '/best': typeof BestRoute
  '/comparisons': typeof ComparisonsRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/gear': typeof GearRoute
  '/how-we-research': typeof HowWeResearchRoute
  '/medical-review-policy': typeof MedicalReviewPolicyRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/review-methodology': typeof ReviewMethodologyRoute
  '/starter-guide': typeof StarterGuideRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/reviews/alo': typeof ReviewsAloRoute
  '/reviews/best-yoga-mats': typeof ReviewsBestYogaMatsRoute
  '/reviews/gaiam': typeof ReviewsGaiamRoute
  '/reviews/jade': typeof ReviewsJadeRoute
  '/reviews/liforme': typeof ReviewsLiformeRoute
  '/reviews/lululemon': typeof ReviewsLululemonRoute
  '/reviews/manduka-grp-adapt': typeof ReviewsMandukaGrpAdaptRoute
  '/reviews/manduka-pro': typeof ReviewsMandukaProRoute
  '/reviews/retrospec': typeof ReviewsRetrospecRoute
  '/blog': typeof BlogIndexRoute
  '/go': typeof GoIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/poses': typeof PosesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/ai-imagery-policy': typeof AiImageryPolicyRoute
  '/best': typeof BestRoute
  '/comparisons': typeof ComparisonsRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/gear': typeof GearRoute
  '/how-we-research': typeof HowWeResearchRoute
  '/medical-review-policy': typeof MedicalReviewPolicyRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/review-methodology': typeof ReviewMethodologyRoute
  '/starter-guide': typeof StarterGuideRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/reviews/alo': typeof ReviewsAloRoute
  '/reviews/best-yoga-mats': typeof ReviewsBestYogaMatsRoute
  '/reviews/gaiam': typeof ReviewsGaiamRoute
  '/reviews/jade': typeof ReviewsJadeRoute
  '/reviews/liforme': typeof ReviewsLiformeRoute
  '/reviews/lululemon': typeof ReviewsLululemonRoute
  '/reviews/manduka-grp-adapt': typeof ReviewsMandukaGrpAdaptRoute
  '/reviews/manduka-pro': typeof ReviewsMandukaProRoute
  '/reviews/retrospec': typeof ReviewsRetrospecRoute
  '/blog/': typeof BlogIndexRoute
  '/go/': typeof GoIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/poses/': typeof PosesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/ai-imagery-policy'
    | '/best'
    | '/comparisons'
    | '/confirm'
    | '/contact'
    | '/corrections-policy'
    | '/editorial-policy'
    | '/gear'
    | '/how-we-research'
    | '/medical-review-policy'
    | '/practice'
    | '/privacy'
    | '/review-methodology'
    | '/starter-guide'
    | '/terms'
    | '/unsubscribe'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/reviews/alo'
    | '/reviews/best-yoga-mats'
    | '/reviews/gaiam'
    | '/reviews/jade'
    | '/reviews/liforme'
    | '/reviews/lululemon'
    | '/reviews/manduka-grp-adapt'
    | '/reviews/manduka-pro'
    | '/reviews/retrospec'
    | '/blog/'
    | '/go/'
    | '/guides/'
    | '/poses/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/ai-imagery-policy'
    | '/best'
    | '/comparisons'
    | '/confirm'
    | '/contact'
    | '/corrections-policy'
    | '/editorial-policy'
    | '/gear'
    | '/how-we-research'
    | '/medical-review-policy'
    | '/practice'
    | '/privacy'
    | '/review-methodology'
    | '/starter-guide'
    | '/terms'
    | '/unsubscribe'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/reviews/alo'
    | '/reviews/best-yoga-mats'
    | '/reviews/gaiam'
    | '/reviews/jade'
    | '/reviews/liforme'
    | '/reviews/lululemon'
    | '/reviews/manduka-grp-adapt'
    | '/reviews/manduka-pro'
    | '/reviews/retrospec'
    | '/blog'
    | '/go'
    | '/guides'
    | '/poses'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/ai-imagery-policy'
    | '/best'
    | '/comparisons'
    | '/confirm'
    | '/contact'
    | '/corrections-policy'
    | '/editorial-policy'
    | '/gear'
    | '/how-we-research'
    | '/medical-review-policy'
    | '/practice'
    | '/privacy'
    | '/review-methodology'
    | '/starter-guide'
    | '/terms'
    | '/unsubscribe'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/reviews/alo'
    | '/reviews/best-yoga-mats'
    | '/reviews/gaiam'
    | '/reviews/jade'
    | '/reviews/liforme'
    | '/reviews/lululemon'
    | '/reviews/manduka-grp-adapt'
    | '/reviews/manduka-pro'
    | '/reviews/retrospec'
    | '/blog/'
    | '/go/'
    | '/guides/'
    | '/poses/'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AiImageryPolicyRoute: typeof AiImageryPolicyRoute
  BestRoute: typeof BestRoute
  ComparisonsRoute: typeof ComparisonsRoute
  ConfirmRoute: typeof ConfirmRoute
  ContactRoute: typeof ContactRoute
  CorrectionsPolicyRoute: typeof CorrectionsPolicyRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  GearRoute: typeof GearRoute
  HowWeResearchRoute: typeof HowWeResearchRoute
  MedicalReviewPolicyRoute: typeof MedicalReviewPolicyRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewMethodologyRoute: typeof ReviewMethodologyRoute
  StarterGuideRoute: typeof StarterGuideRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PosesSlugRoute: typeof PosesSlugRoute
  ReviewsAloRoute: typeof ReviewsAloRoute
  ReviewsBestYogaMatsRoute: typeof ReviewsBestYogaMatsRoute
  ReviewsGaiamRoute: typeof ReviewsGaiamRoute
  ReviewsJadeRoute: typeof ReviewsJadeRoute
  ReviewsLiformeRoute: typeof ReviewsLiformeRoute
  ReviewsLululemonRoute: typeof ReviewsLululemonRoute
  ReviewsMandukaGrpAdaptRoute: typeof ReviewsMandukaGrpAdaptRoute
  ReviewsMandukaProRoute: typeof ReviewsMandukaProRoute
  ReviewsRetrospecRoute: typeof ReviewsRetrospecRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GoIndexRoute: typeof GoIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PosesIndexRoute: typeof PosesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-guide': {
      id: '/starter-guide'
      path: '/starter-guide'
      fullPath: '/starter-guide'
      preLoaderRoute: typeof StarterGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-methodology': {
      id: '/review-methodology'
      path: '/review-methodology'
      fullPath: '/review-methodology'
      preLoaderRoute: typeof ReviewMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-review-policy': {
      id: '/medical-review-policy'
      path: '/medical-review-policy'
      fullPath: '/medical-review-policy'
      preLoaderRoute: typeof MedicalReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-research': {
      id: '/how-we-research'
      path: '/how-we-research'
      fullPath: '/how-we-research'
      preLoaderRoute: typeof HowWeResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections-policy': {
      id: '/corrections-policy'
      path: '/corrections-policy'
      fullPath: '/corrections-policy'
      preLoaderRoute: typeof CorrectionsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparisons': {
      id: '/comparisons'
      path: '/comparisons'
      fullPath: '/comparisons'
      preLoaderRoute: typeof ComparisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best': {
      id: '/best'
      path: '/best'
      fullPath: '/best'
      preLoaderRoute: typeof BestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-imagery-policy': {
      id: '/ai-imagery-policy'
      path: '/ai-imagery-policy'
      fullPath: '/ai-imagery-policy'
      preLoaderRoute: typeof AiImageryPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poses/': {
      id: '/poses/'
      path: '/poses'
      fullPath: '/poses/'
      preLoaderRoute: typeof PosesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/': {
      id: '/go/'
      path: '/go'
      fullPath: '/go/'
      preLoaderRoute: typeof GoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/retrospec': {
      id: '/reviews/retrospec'
      path: '/reviews/retrospec'
      fullPath: '/reviews/retrospec'
      preLoaderRoute: typeof ReviewsRetrospecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/manduka-pro': {
      id: '/reviews/manduka-pro'
      path: '/reviews/manduka-pro'
      fullPath: '/reviews/manduka-pro'
      preLoaderRoute: typeof ReviewsMandukaProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/manduka-grp-adapt': {
      id: '/reviews/manduka-grp-adapt'
      path: '/reviews/manduka-grp-adapt'
      fullPath: '/reviews/manduka-grp-adapt'
      preLoaderRoute: typeof ReviewsMandukaGrpAdaptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/lululemon': {
      id: '/reviews/lululemon'
      path: '/reviews/lululemon'
      fullPath: '/reviews/lululemon'
      preLoaderRoute: typeof ReviewsLululemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/liforme': {
      id: '/reviews/liforme'
      path: '/reviews/liforme'
      fullPath: '/reviews/liforme'
      preLoaderRoute: typeof ReviewsLiformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/jade': {
      id: '/reviews/jade'
      path: '/reviews/jade'
      fullPath: '/reviews/jade'
      preLoaderRoute: typeof ReviewsJadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/gaiam': {
      id: '/reviews/gaiam'
      path: '/reviews/gaiam'
      fullPath: '/reviews/gaiam'
      preLoaderRoute: typeof ReviewsGaiamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/best-yoga-mats': {
      id: '/reviews/best-yoga-mats'
      path: '/reviews/best-yoga-mats'
      fullPath: '/reviews/best-yoga-mats'
      preLoaderRoute: typeof ReviewsBestYogaMatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/alo': {
      id: '/reviews/alo'
      path: '/reviews/alo'
      fullPath: '/reviews/alo'
      preLoaderRoute: typeof ReviewsAloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poses/$slug': {
      id: '/poses/$slug'
      path: '/poses/$slug'
      fullPath: '/poses/$slug'
      preLoaderRoute: typeof PosesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AiImageryPolicyRoute: AiImageryPolicyRoute,
  BestRoute: BestRoute,
  ComparisonsRoute: ComparisonsRoute,
  ConfirmRoute: ConfirmRoute,
  ContactRoute: ContactRoute,
  CorrectionsPolicyRoute: CorrectionsPolicyRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  GearRoute: GearRoute,
  HowWeResearchRoute: HowWeResearchRoute,
  MedicalReviewPolicyRoute: MedicalReviewPolicyRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewMethodologyRoute: ReviewMethodologyRoute,
  StarterGuideRoute: StarterGuideRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  GoSlugRoute: GoSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PosesSlugRoute: PosesSlugRoute,
  ReviewsAloRoute: ReviewsAloRoute,
  ReviewsBestYogaMatsRoute: ReviewsBestYogaMatsRoute,
  ReviewsGaiamRoute: ReviewsGaiamRoute,
  ReviewsJadeRoute: ReviewsJadeRoute,
  ReviewsLiformeRoute: ReviewsLiformeRoute,
  ReviewsLululemonRoute: ReviewsLululemonRoute,
  ReviewsMandukaGrpAdaptRoute: ReviewsMandukaGrpAdaptRoute,
  ReviewsMandukaProRoute: ReviewsMandukaProRoute,
  ReviewsRetrospecRoute: ReviewsRetrospecRoute,
  BlogIndexRoute: BlogIndexRoute,
  GoIndexRoute: GoIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PosesIndexRoute: PosesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
