/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StarterGuideRouteImport } from './routes/starter-guide'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosesIndexRouteImport } from './routes/poses/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GoIndexRouteImport } from './routes/go/index'
import { Route as ReviewsRetrospecRouteImport } from './routes/reviews/retrospec'
import { Route as ReviewsMandukaProRouteImport } from './routes/reviews/manduka-pro'
import { Route as ReviewsLululemonRouteImport } from './routes/reviews/lululemon'
import { Route as ReviewsLiformeRouteImport } from './routes/reviews/liforme'
import { Route as ReviewsJadeRouteImport } from './routes/reviews/jade'
import { Route as ReviewsGaiamRouteImport } from './routes/reviews/gaiam'
import { Route as ReviewsBestYogaMatsRouteImport } from './routes/reviews/best-yoga-mats'
import { Route as PosesSlugRouteImport } from './routes/poses/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors/$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterGuideRoute = StarterGuideRouteImport.update({
  id: '/starter-guide',
  path: '/starter-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosesIndexRoute = PosesIndexRouteImport.update({
  id: '/poses/',
  path: '/poses/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoIndexRoute = GoIndexRouteImport.update({
  id: '/go/',
  path: '/go/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRetrospecRoute = ReviewsRetrospecRouteImport.update({
  id: '/reviews/retrospec',
  path: '/reviews/retrospec',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsMandukaProRoute = ReviewsMandukaProRouteImport.update({
  id: '/reviews/manduka-pro',
  path: '/reviews/manduka-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsLululemonRoute = ReviewsLululemonRouteImport.update({
  id: '/reviews/lululemon',
  path: '/reviews/lululemon',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsLiformeRoute = ReviewsLiformeRouteImport.update({
  id: '/reviews/liforme',
  path: '/reviews/liforme',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsJadeRoute = ReviewsJadeRouteImport.update({
  id: '/reviews/jade',
  path: '/reviews/jade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsGaiamRoute = ReviewsGaiamRouteImport.update({
  id: '/reviews/gaiam',
  path: '/reviews/gaiam',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsBestYogaMatsRoute = ReviewsBestYogaMatsRouteImport.update({
  id: '/reviews/best-yoga-mats',
  path: '/reviews/best-yoga-mats',
  getParentRoute: () => rootRouteImport,
} as any)
const PosesSlugRoute = PosesSlugRouteImport.update({
  id: '/poses/$slug',
  path: '/poses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/starter-guide': typeof StarterGuideRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/reviews/best-yoga-mats': typeof ReviewsBestYogaMatsRoute
  '/reviews/gaiam': typeof ReviewsGaiamRoute
  '/reviews/jade': typeof ReviewsJadeRoute
  '/reviews/liforme': typeof ReviewsLiformeRoute
  '/reviews/lululemon': typeof ReviewsLululemonRoute
  '/reviews/manduka-pro': typeof ReviewsMandukaProRoute
  '/reviews/retrospec': typeof ReviewsRetrospecRoute
  '/go/': typeof GoIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/poses/': typeof PosesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/starter-guide': typeof StarterGuideRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/reviews/best-yoga-mats': typeof ReviewsBestYogaMatsRoute
  '/reviews/gaiam': typeof ReviewsGaiamRoute
  '/reviews/jade': typeof ReviewsJadeRoute
  '/reviews/liforme': typeof ReviewsLiformeRoute
  '/reviews/lululemon': typeof ReviewsLululemonRoute
  '/reviews/manduka-pro': typeof ReviewsMandukaProRoute
  '/reviews/retrospec': typeof ReviewsRetrospecRoute
  '/go': typeof GoIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/poses': typeof PosesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/starter-guide': typeof StarterGuideRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/reviews/best-yoga-mats': typeof ReviewsBestYogaMatsRoute
  '/reviews/gaiam': typeof ReviewsGaiamRoute
  '/reviews/jade': typeof ReviewsJadeRoute
  '/reviews/liforme': typeof ReviewsLiformeRoute
  '/reviews/lululemon': typeof ReviewsLululemonRoute
  '/reviews/manduka-pro': typeof ReviewsMandukaProRoute
  '/reviews/retrospec': typeof ReviewsRetrospecRoute
  '/go/': typeof GoIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/poses/': typeof PosesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/confirm'
    | '/contact'
    | '/privacy'
    | '/starter-guide'
    | '/terms'
    | '/unsubscribe'
    | '/authors/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/reviews/best-yoga-mats'
    | '/reviews/gaiam'
    | '/reviews/jade'
    | '/reviews/liforme'
    | '/reviews/lululemon'
    | '/reviews/manduka-pro'
    | '/reviews/retrospec'
    | '/go/'
    | '/guides/'
    | '/poses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/confirm'
    | '/contact'
    | '/privacy'
    | '/starter-guide'
    | '/terms'
    | '/unsubscribe'
    | '/authors/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/reviews/best-yoga-mats'
    | '/reviews/gaiam'
    | '/reviews/jade'
    | '/reviews/liforme'
    | '/reviews/lululemon'
    | '/reviews/manduka-pro'
    | '/reviews/retrospec'
    | '/go'
    | '/guides'
    | '/poses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/confirm'
    | '/contact'
    | '/privacy'
    | '/starter-guide'
    | '/terms'
    | '/unsubscribe'
    | '/authors/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/reviews/best-yoga-mats'
    | '/reviews/gaiam'
    | '/reviews/jade'
    | '/reviews/liforme'
    | '/reviews/lululemon'
    | '/reviews/manduka-pro'
    | '/reviews/retrospec'
    | '/go/'
    | '/guides/'
    | '/poses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  ConfirmRoute: typeof ConfirmRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  StarterGuideRoute: typeof StarterGuideRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PosesSlugRoute: typeof PosesSlugRoute
  ReviewsBestYogaMatsRoute: typeof ReviewsBestYogaMatsRoute
  ReviewsGaiamRoute: typeof ReviewsGaiamRoute
  ReviewsJadeRoute: typeof ReviewsJadeRoute
  ReviewsLiformeRoute: typeof ReviewsLiformeRoute
  ReviewsLululemonRoute: typeof ReviewsLululemonRoute
  ReviewsMandukaProRoute: typeof ReviewsMandukaProRoute
  ReviewsRetrospecRoute: typeof ReviewsRetrospecRoute
  GoIndexRoute: typeof GoIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PosesIndexRoute: typeof PosesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-guide': {
      id: '/starter-guide'
      path: '/starter-guide'
      fullPath: '/starter-guide'
      preLoaderRoute: typeof StarterGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poses/': {
      id: '/poses/'
      path: '/poses'
      fullPath: '/poses/'
      preLoaderRoute: typeof PosesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/': {
      id: '/go/'
      path: '/go'
      fullPath: '/go/'
      preLoaderRoute: typeof GoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/retrospec': {
      id: '/reviews/retrospec'
      path: '/reviews/retrospec'
      fullPath: '/reviews/retrospec'
      preLoaderRoute: typeof ReviewsRetrospecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/manduka-pro': {
      id: '/reviews/manduka-pro'
      path: '/reviews/manduka-pro'
      fullPath: '/reviews/manduka-pro'
      preLoaderRoute: typeof ReviewsMandukaProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/lululemon': {
      id: '/reviews/lululemon'
      path: '/reviews/lululemon'
      fullPath: '/reviews/lululemon'
      preLoaderRoute: typeof ReviewsLululemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/liforme': {
      id: '/reviews/liforme'
      path: '/reviews/liforme'
      fullPath: '/reviews/liforme'
      preLoaderRoute: typeof ReviewsLiformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/jade': {
      id: '/reviews/jade'
      path: '/reviews/jade'
      fullPath: '/reviews/jade'
      preLoaderRoute: typeof ReviewsJadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/gaiam': {
      id: '/reviews/gaiam'
      path: '/reviews/gaiam'
      fullPath: '/reviews/gaiam'
      preLoaderRoute: typeof ReviewsGaiamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/best-yoga-mats': {
      id: '/reviews/best-yoga-mats'
      path: '/reviews/best-yoga-mats'
      fullPath: '/reviews/best-yoga-mats'
      preLoaderRoute: typeof ReviewsBestYogaMatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poses/$slug': {
      id: '/poses/$slug'
      path: '/poses/$slug'
      fullPath: '/poses/$slug'
      preLoaderRoute: typeof PosesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  ConfirmRoute: ConfirmRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  StarterGuideRoute: StarterGuideRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  GoSlugRoute: GoSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PosesSlugRoute: PosesSlugRoute,
  ReviewsBestYogaMatsRoute: ReviewsBestYogaMatsRoute,
  ReviewsGaiamRoute: ReviewsGaiamRoute,
  ReviewsJadeRoute: ReviewsJadeRoute,
  ReviewsLiformeRoute: ReviewsLiformeRoute,
  ReviewsLululemonRoute: ReviewsLululemonRoute,
  ReviewsMandukaProRoute: ReviewsMandukaProRoute,
  ReviewsRetrospecRoute: ReviewsRetrospecRoute,
  GoIndexRoute: GoIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PosesIndexRoute: PosesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
