/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoIndexRouteImport } from './routes/go/index'
import { Route as PosesSlugRouteImport } from './routes/poses/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoIndexRoute = GoIndexRouteImport.update({
  id: '/go/',
  path: '/go/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosesSlugRoute = PosesSlugRouteImport.update({
  id: '/poses/$slug',
  path: '/poses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/go/': typeof GoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/go': typeof GoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/poses/$slug': typeof PosesSlugRoute
  '/go/': typeof GoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/confirm'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/authors/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/go/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/confirm'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/authors/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/go'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/confirm'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/authors/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/poses/$slug'
    | '/go/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  ConfirmRoute: typeof ConfirmRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PosesSlugRoute: typeof PosesSlugRoute
  GoIndexRoute: typeof GoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/': {
      id: '/go/'
      path: '/go'
      fullPath: '/go/'
      preLoaderRoute: typeof GoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poses/$slug': {
      id: '/poses/$slug'
      path: '/poses/$slug'
      fullPath: '/poses/$slug'
      preLoaderRoute: typeof PosesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  ConfirmRoute: ConfirmRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  GoSlugRoute: GoSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PosesSlugRoute: PosesSlugRoute,
  GoIndexRoute: GoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
